"use strict";
var berial = 'berialyue';
var yueduming = new String('berial');
console.log(berial);
console.log(yueduming);
console.log(berial.length);
console.log(yueduming.length);
var something = "清早起来打开窗，心情美美的，我要出去找小姐姐，心情美美的。";
var xiaoJieJie = "小姐姐";
console.log(something.indexOf(xiaoJieJie));
console.log(something.lastIndexOf(xiaoJieJie));
console.log(something.substring(8));
console.log(something.substring(8, 14));
console.log(something.replace(xiaoJieJie, '小哥哥'));
